name: koumen

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: koumen
      POSTGRES_USER: koumen
      POSTGRES_PASSWORD: koumen123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6399:6379'

volumes:
  pgdata:
