import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Shop } from '../shops/shop.entity';

interface SeedShop {
  name: string;
  city: string;
  district: string;
  neighborhood: string;
  address: string;
  lat: number;
  lng: number;
  category: string;
  avgPrice: number;
  rating: number;
  imageUrl: string;
  discountTypes: string[];
  discounts: Record<string, string>;
  externalUrl: string;
  platform: string;
  openHours: Record<string, string>;
  externalId: string;
}

const SEED_SHOPS: SeedShop[] = [
  // ========== 龙华会（17家） ==========
  {
    name: '松鹤楼苏式汤面',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会B1层',
    lat: 31.1895,
    lng: 121.4542,
    category: '本帮沪菜',
    avgPrice: 60,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/songhelou.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '早市满30减10' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_001',
    platform: 'dianping',
    openHours: { weekday: '07:00-21:00', weekend: '07:00-21:00' },
    externalId: 'sh_lh_001',
  },
  {
    name: '柿合缘新京菜',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会3层',
    lat: 31.1888,
    lng: 121.4535,
    category: '风味地方菜',
    avgPrice: 280,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/shiheyuan.jpg',
    discountTypes: ['团购'],
    discounts: { 团购: '团购套餐9折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_002',
    platform: 'dianping',
    openHours: { weekday: '11:00-21:00', weekend: '10:30-21:30' },
    externalId: 'sh_lh_002',
  },
  {
    name: '逸道精致中餐',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会4层',
    lat: 31.189,
    lng: 121.454,
    category: '江浙菜',
    avgPrice: 200,
    rating: 4.4,
    imageUrl: 'https://p0.meituan.net/brandlogons/yidao.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '工作日午市8折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_003',
    platform: 'dianping',
    openHours: { weekday: '11:00-14:00,17:00-21:00', weekend: '11:00-21:00' },
    externalId: 'sh_lh_003',
  },
  {
    name: '四面泰',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会2层',
    lat: 31.1893,
    lng: 121.4538,
    category: '泰国料理',
    avgPrice: 110,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/simiantai.jpg',
    discountTypes: ['团购'],
    discounts: { 团购: '双人套餐立减30' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_004',
    platform: 'dianping',
    openHours: { weekday: '11:00-21:30', weekend: '10:30-22:00' },
    externalId: 'sh_lh_004',
  },
  {
    name: '趁烧火锅',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L3层',
    lat: 31.1891,
    lng: 121.4543,
    category: '烧烤烤肉',
    avgPrice: 190,
    rating: 4.7,
    imageUrl: 'https://p0.meituan.net/brandlogons/chenshao.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '全国唯一店·工作日8.5折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_005',
    platform: 'dianping',
    openHours: { weekday: '11:30-22:00', weekend: '11:00-22:30' },
    externalId: 'sh_lh_005',
  },
  {
    name: "Grande A'moo甜品",
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L1层',
    lat: 31.1887,
    lng: 121.4537,
    category: '甜品蛋糕',
    avgPrice: 55,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/grandeamoo.jpg',
    discountTypes: ['神券'],
    discounts: { 神券: '新客立减10元' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_006',
    platform: 'dianping',
    openHours: { weekday: '10:00-21:00', weekend: '10:00-21:30' },
    externalId: 'sh_lh_006',
  },
  {
    name: 'MANNER咖啡(龙华会)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L1层',
    lat: 31.1894,
    lng: 121.4541,
    category: '咖啡奶茶',
    avgPrice: 22,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/manner.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '自带杯减5元' },
    externalUrl: 'https://www.meituan.com/meishi/sh_lh_007',
    platform: 'meituan',
    openHours: { weekday: '08:00-21:00', weekend: '08:30-21:00' },
    externalId: 'sh_lh_007',
  },
  {
    name: '开吉茶馆',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会',
    lat: 31.1889,
    lng: 121.4536,
    category: '咖啡奶茶',
    avgPrice: 45,
    rating: 4.4,
    imageUrl: 'https://p0.meituan.net/brandlogons/kaiji.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '下午3点后买一送一' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_008',
    platform: 'dianping',
    openHours: { weekday: '09:00-21:00', weekend: '09:00-21:30' },
    externalId: 'sh_lh_008',
  },
  {
    name: 'RCKLESS自然酒馆',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会',
    lat: 31.1896,
    lng: 121.4544,
    category: '自然酒馆',
    avgPrice: 120,
    rating: 4.3,
    imageUrl: 'https://p0.meituan.net/brandlogons/rckless.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '工作日欢乐时光6折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_009',
    platform: 'dianping',
    openHours: { weekday: '16:00-翌日02:00', weekend: '14:00-翌日02:00' },
    externalId: 'sh_lh_009',
  },
  {
    name: '奥乐齐ALDI(龙华会)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会B1层',
    lat: 31.1884,
    lng: 121.4534,
    category: '购物',
    avgPrice: 80,
    rating: 4.7,
    imageUrl: 'https://p0.meituan.net/brandlogons/aldi.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '自有品牌会员享积分' },
    externalUrl: 'https://www.meituan.com/meishi/sh_lh_010',
    platform: 'meituan',
    openHours: { weekday: '07:00-22:00', weekend: '07:00-22:00' },
    externalId: 'sh_lh_010',
  },
  {
    name: '优衣库(龙华会)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L2层',
    lat: 31.1892,
    lng: 121.4533,
    category: '购物',
    avgPrice: 200,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/uniqlo.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: 'UT联名/周限定折扣' },
    externalUrl: 'https://www.meituan.com/meishi/sh_lh_011',
    platform: 'meituan',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_011',
  },
  {
    name: '魅KTV(龙华会)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L4层',
    lat: 31.1886,
    lng: 121.4546,
    category: 'KTV',
    avgPrice: 90,
    rating: 4.3,
    imageUrl: 'https://p0.meituan.net/brandlogons/meiktv.jpg',
    discountTypes: ['团购'],
    discounts: { 团购: '小程序预约享7折·工作日套餐' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_012',
    platform: 'dianping',
    openHours: { weekday: '13:00-翌日02:00', weekend: '12:00-翌日02:00' },
    externalId: 'sh_lh_012',
  },
  {
    name: 'GOEASY够意思',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L2层',
    lat: 31.1897,
    lng: 121.4531,
    category: '户外运动',
    avgPrice: 600,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/goeasy.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '会员首购9折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_013',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_013',
  },
  {
    name: 'UNDEFEATED',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L2层',
    lat: 31.1883,
    lng: 121.4548,
    category: '潮流服饰',
    avgPrice: 1200,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/undefeated.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: 'https://www.dianping.com/shop/sh_lh_014',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_014',
  },
  {
    name: 'ARMY LOGIC',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L2层',
    lat: 31.1899,
    lng: 121.4529,
    category: '潮流服饰',
    avgPrice: 450,
    rating: 4.3,
    imageUrl: 'https://p0.meituan.net/brandlogons/armylogic.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '季末折扣最高5折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_015',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_015',
  },
  {
    name: '甬府尊鲜',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会L3层',
    lat: 31.1881,
    lng: 121.455,
    category: '鱼鲜海鲜',
    avgPrice: 400,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/yongfu.jpg',
    discountTypes: ['团购'],
    discounts: { 团购: '商务套餐预约享赠品' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_016',
    platform: 'dianping',
    openHours: { weekday: '11:00-21:30', weekend: '11:00-22:00' },
    externalId: 'sh_lh_016',
  },
  {
    name: '龙华会夜市摊位',
    city: '上海',
    district: '徐汇区',
    neighborhood: '龙华会',
    address: '徐汇区龙华路2778号龙华会妙街',
    lat: 31.19,
    lng: 121.4527,
    category: '小吃简餐',
    avgPrice: 30,
    rating: 4.4,
    imageUrl: 'https://p0.meituan.net/brandlogons/yeshi.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: '',
    platform: 'dianping',
    openHours: { weekday: '17:00-22:00', weekend: '15:00-23:00' },
    externalId: 'sh_lh_017',
  },
  // ========== 西岸凤巢（7家） ==========
  {
    name: 'M Stand(西岸凤巢)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸凤巢',
    address: '徐汇区云锦路683号西岸凤巢',
    lat: 31.1718,
    lng: 121.4638,
    category: '咖啡奶茶',
    avgPrice: 45,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/mstand.jpg',
    discountTypes: ['神券'],
    discounts: { 神券: '首杯新客立减8元' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_018',
    platform: 'dianping',
    openHours: { weekday: '08:00-22:00', weekend: '08:30-22:00' },
    externalId: 'sh_lh_018',
  },
  {
    name: 'SeeSaw Coffee',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸凤巢',
    address: '徐汇区云锦路683号西岸凤巢L1层',
    lat: 31.1711,
    lng: 121.4632,
    category: '咖啡奶茶',
    avgPrice: 48,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/seesawcoffee.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '积分换购周边' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_019',
    platform: 'dianping',
    openHours: { weekday: '08:30-21:30', weekend: '09:00-22:00' },
    externalId: 'sh_lh_019',
  },
  {
    name: '蔡嘉法式甜品',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸凤巢',
    address: '徐汇区云锦路683号西岸凤巢',
    lat: 31.1716,
    lng: 121.4641,
    category: '甜品蛋糕',
    avgPrice: 85,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/caijia.jpg',
    discountTypes: ['团购'],
    discounts: { 团购: '双份套餐9折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_020',
    platform: 'dianping',
    openHours: { weekday: '10:00-21:00', weekend: '10:00-21:30' },
    externalId: 'sh_lh_020',
  },
  {
    name: 'LeTAO',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸凤巢',
    address: '徐汇区云锦路683号西岸凤巢L1层',
    lat: 31.1712,
    lng: 121.4629,
    category: '甜品蛋糕',
    avgPrice: 70,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/letao.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '招牌双层芝士蛋糕买2送1' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_021',
    platform: 'dianping',
    openHours: { weekday: '10:00-21:00', weekend: '10:00-21:30' },
    externalId: 'sh_lh_021',
  },
  {
    name: 'FIKA WAKA',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸凤巢',
    address: '徐汇区云锦路683号西岸凤巢',
    lat: 31.172,
    lng: 121.4644,
    category: '咖啡奶茶',
    avgPrice: 90,
    rating: 4.4,
    imageUrl: 'https://p0.meituan.net/brandlogons/fikawaka.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: 'https://www.dianping.com/shop/sh_lh_022',
    platform: 'dianping',
    openHours: { weekday: '09:00-21:00', weekend: '09:00-21:30' },
    externalId: 'sh_lh_022',
  },
  {
    name: '奈尔宝科技馆',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸凤巢',
    address: '徐汇区云锦路683号西岸凤巢L3层',
    lat: 31.1708,
    lng: 121.4626,
    category: '亲子科技',
    avgPrice: 220,
    rating: 4.7,
    imageUrl: 'https://p0.meituan.net/brandlogons/naerbao.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '会员早场享8折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_023',
    platform: 'dianping',
    openHours: { weekday: '10:00-20:00', weekend: '09:30-21:00' },
    externalId: 'sh_lh_023',
  },
  {
    name: '三体沉浸式体验馆',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸凤巢',
    address: '徐汇区云锦路683号西岸凤巢L4层',
    lat: 31.1722,
    lng: 121.4647,
    category: '沉浸体验',
    avgPrice: 150,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/santi.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '工作日立减30元' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_024',
    platform: 'dianping',
    openHours: { weekday: '10:00-21:00', weekend: '10:00-21:30' },
    externalId: 'sh_lh_024',
  },
  // ========== 西岸梦中心（20家） ==========
  {
    name: '蓝瓶咖啡Blue Bottle',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L1层',
    lat: 31.157,
    lng: 121.4695,
    category: '咖啡奶茶',
    avgPrice: 60,
    rating: 4.8,
    imageUrl: 'https://p0.meituan.net/brandlogons/bluebottle.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: 'https://www.dianping.com/shop/sh_lh_025',
    platform: 'dianping',
    openHours: { weekday: '08:00-22:00', weekend: '08:00-22:00' },
    externalId: 'sh_lh_025',
  },
  {
    name: 'M Stand(梦中心江边店)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心滨江层',
    lat: 31.1564,
    lng: 121.4688,
    category: '咖啡奶茶',
    avgPrice: 45,
    rating: 4.7,
    imageUrl: 'https://p0.meituan.net/brandlogons/mstand.jpg',
    discountTypes: [],
    discounts: { 特色: '江景座位免预约' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_026',
    platform: 'dianping',
    openHours: { weekday: '08:00-22:00', weekend: '08:00-22:00' },
    externalId: 'sh_lh_026',
  },
  {
    name: '阿嬷手作',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L1层',
    lat: 31.1573,
    lng: 121.4701,
    category: '甜品蛋糕',
    avgPrice: 35,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/ama.jpg',
    discountTypes: ['团购'],
    discounts: { 团购: '10人以上团购9折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_027',
    platform: 'dianping',
    openHours: { weekday: '10:00-21:00', weekend: '10:00-21:30' },
    externalId: 'sh_lh_027',
  },
  {
    name: '瓦屋川菜(上海首店)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L3层',
    lat: 31.156,
    lng: 121.4682,
    category: '川湘菜',
    avgPrice: 110,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/wawu.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '新店开业9折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_028',
    platform: 'dianping',
    openHours: { weekday: '11:00-21:30', weekend: '10:30-22:00' },
    externalId: 'sh_lh_028',
  },
  {
    name: '桂芭蕉',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L3层',
    lat: 31.1576,
    lng: 121.4707,
    category: '东南亚菜',
    avgPrice: 200,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/guibajiao.jpg',
    discountTypes: [],
    discounts: { 特色: '需取号等位' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_029',
    platform: 'dianping',
    openHours: { weekday: '11:00-21:30', weekend: '11:00-22:00' },
    externalId: 'sh_lh_029',
  },
  {
    name: '胡麻傣味',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L2层',
    lat: 31.1557,
    lng: 121.4676,
    category: '傣味菜',
    avgPrice: 120,
    rating: 4.4,
    imageUrl: 'https://p0.meituan.net/brandlogons/huma.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '午市套餐立减20' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_030',
    platform: 'dianping',
    openHours: { weekday: '11:00-21:00', weekend: '11:00-21:30' },
    externalId: 'sh_lh_030',
  },
  {
    name: 'Mozzarella e Vino',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L2层',
    lat: 31.1579,
    lng: 121.4713,
    category: '西餐',
    avgPrice: 200,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/mozzarella.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '工作日商务套餐8.5折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_031',
    platform: 'dianping',
    openHours: { weekday: '11:30-22:00', weekend: '11:00-22:30' },
    externalId: 'sh_lh_031',
  },
  {
    name: 'CRAFTED By',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心江边露台',
    lat: 31.1554,
    lng: 121.467,
    category: '西餐',
    avgPrice: 300,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/crafted.jpg',
    discountTypes: [],
    discounts: { 特色: '露台位需提前预约' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_032',
    platform: 'dianping',
    openHours: { weekday: '11:30-22:00', weekend: '11:00-22:30' },
    externalId: 'sh_lh_032',
  },
  {
    name: 'BLOOMARKET美食市集',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L1层',
    lat: 31.1582,
    lng: 121.4719,
    category: '小吃简餐',
    avgPrice: 80,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/bloomarket.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: 'https://www.dianping.com/shop/sh_lh_033',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_033',
  },
  {
    name: 'DiscoTopia舞托邦',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L4层',
    lat: 31.1551,
    lng: 121.4664,
    category: '沉浸体验',
    avgPrice: 180,
    rating: 4.7,
    imageUrl: 'https://p0.meituan.net/brandlogons/discotopia.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '工作日入场票7折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_034',
    platform: 'dianping',
    openHours: { weekday: '14:00-翌日02:00', weekend: '12:00-翌日02:00' },
    externalId: 'sh_lh_034',
  },
  {
    name: 'Aark Space',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心',
    lat: 31.1585,
    lng: 121.4725,
    category: '沉浸体验',
    avgPrice: 150,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/aarkspace.jpg',
    discountTypes: ['神券'],
    discounts: { 神券: '新客首次体验8折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_035',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_035',
  },
  {
    name: 'SFC露天水岸剧场',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心江边',
    lat: 31.1548,
    lng: 121.4658,
    category: '艺术展览',
    avgPrice: 80,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/sfc.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '早鸟票9折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_036',
    platform: 'dianping',
    openHours: { weekday: '19:00-23:00', weekend: '14:00-23:00' },
    externalId: 'sh_lh_036',
  },
  {
    name: 'lululemon(梦中心)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L2层',
    lat: 31.1588,
    lng: 121.4731,
    category: '户外运动',
    avgPrice: 800,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/lululemon.jpg',
    discountTypes: [],
    discounts: { 特色: '周末社群活动免费' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_037',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_037',
  },
  {
    name: 'On昂跑跑者基地',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L1层',
    lat: 31.1545,
    lng: 121.4652,
    category: '户外运动',
    avgPrice: 1000,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/on.jpg',
    discountTypes: [],
    discounts: { 特色: '体验跑步活动免费' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_038',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_038',
  },
  {
    name: 'Patagonia',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L2层',
    lat: 31.1591,
    lng: 121.4737,
    category: '户外运动',
    avgPrice: 1500,
    rating: 4.7,
    imageUrl: 'https://p0.meituan.net/brandlogons/patagonia.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: 'https://www.dianping.com/shop/sh_lh_039',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_039',
  },
  {
    name: 'Mammut猛犸象',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L2层',
    lat: 31.1542,
    lng: 121.4646,
    category: '户外运动',
    avgPrice: 1500,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/mammut.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: 'https://www.dianping.com/shop/sh_lh_040',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_040',
  },
  {
    name: 'HELLY HANSEN',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L2层',
    lat: 31.1594,
    lng: 121.4743,
    category: '户外运动',
    avgPrice: 1200,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/hellyhansen.jpg',
    discountTypes: [],
    discounts: {},
    externalUrl: 'https://www.dianping.com/shop/sh_lh_041',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_041',
  },
  {
    name: 'BAPE GALLERY™',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L1层',
    lat: 31.1539,
    lng: 121.464,
    category: '潮流服饰',
    avgPrice: 1800,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/bape.jpg',
    discountTypes: [],
    discounts: { 特色: '艺术联名限量' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_042',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_042',
  },
  {
    name: 'EXI.T',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心L2层',
    lat: 31.1597,
    lng: 121.4749,
    category: '潮流服饰',
    avgPrice: 500,
    rating: 4.4,
    imageUrl: 'https://p0.meituan.net/brandlogons/exit.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '季末清仓6折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_043',
    platform: 'dianping',
    openHours: { weekday: '10:00-22:00', weekend: '10:00-22:00' },
    externalId: 'sh_lh_043',
  },
  {
    name: '西岸梦中心停车场',
    city: '上海',
    district: '徐汇区',
    neighborhood: '西岸梦中心',
    address: '徐汇区龙腾大道2260号西岸梦中心B1-B3层',
    lat: 31.1536,
    lng: 121.4634,
    category: '户外公园',
    avgPrice: 0,
    rating: 4.0,
    imageUrl: 'https://p0.meituan.net/brandlogons/parking.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '消费满200免停车费' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_044',
    platform: 'dianping',
    openHours: { weekday: '00:00-24:00', weekend: '00:00-24:00' },
    externalId: 'sh_lh_044',
  },
  // ========== 朵云轩艺术中心（4家） ==========
  {
    name: '朵云轩杜比全景声影城',
    city: '上海',
    district: '徐汇区',
    neighborhood: '朵云轩',
    address: '徐汇区天钥桥路1188号朵云轩艺术中心',
    lat: 31.1787,
    lng: 121.4532,
    category: '电影院',
    avgPrice: 85,
    rating: 4.8,
    imageUrl: 'https://p0.meituan.net/brandlogons/duoyunxuan_cinema.jpg',
    discountTypes: ['促销', '神券'],
    discounts: { 促销: '工作日场次立减20', 神券: '会员积分兑票' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_045',
    platform: 'dianping',
    openHours: { weekday: '10:00-23:00', weekend: '09:30-23:30' },
    externalId: 'sh_lh_045',
  },
  {
    name: '朵云轩美术馆',
    city: '上海',
    district: '徐汇区',
    neighborhood: '朵云轩',
    address: '徐汇区天钥桥路1188号朵云轩艺术中心',
    lat: 31.1781,
    lng: 121.4526,
    category: '艺术展览',
    avgPrice: 30,
    rating: 4.7,
    imageUrl: 'https://p0.meituan.net/brandlogons/duoyunxuan_art.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '部分展览免费·学生5折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_046',
    platform: 'dianping',
    openHours: { weekday: '10:00-17:00', weekend: '10:00-17:00' },
    externalId: 'sh_lh_046',
  },
  {
    name: '朵云轩博物馆',
    city: '上海',
    district: '徐汇区',
    neighborhood: '朵云轩',
    address: '徐汇区天钥桥路1188号朵云轩艺术中心',
    lat: 31.1784,
    lng: 121.4529,
    category: '非遗体验',
    avgPrice: 0,
    rating: 4.6,
    imageUrl: 'https://p0.meituan.net/brandlogons/duoyunxuan_museum.jpg',
    discountTypes: [],
    discounts: { 特色: '常设展免费' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_047',
    platform: 'dianping',
    openHours: { weekday: '09:00-17:00', weekend: '09:00-17:00' },
    externalId: 'sh_lh_047',
  },
  {
    name: '南方非遗展示中心',
    city: '上海',
    district: '徐汇区',
    neighborhood: '朵云轩',
    address: '徐汇区天钥桥路1188号朵云轩艺术中心附近',
    lat: 31.1778,
    lng: 121.4523,
    category: '非遗体验',
    avgPrice: 0,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/nanfangfeiye.jpg',
    discountTypes: [],
    discounts: { 特色: '全部免费' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_048',
    platform: 'dianping',
    openHours: { weekday: '09:00-17:00', weekend: '09:00-17:00' },
    externalId: 'sh_lh_048',
  },
  // ========== 滨江步道及其他（4家） ==========
  {
    name: '归朝欢国风照相馆',
    city: '上海',
    district: '徐汇区',
    neighborhood: '滨江步道',
    address: '徐汇区徐汇滨江附近',
    lat: 31.1653,
    lng: 121.4683,
    category: '文化体验',
    avgPrice: 350,
    rating: 4.8,
    imageUrl: 'https://p0.meituan.net/brandlogons/guizhaohuan.jpg',
    discountTypes: ['团购'],
    discounts: { 团购: '闺蜜双人套餐9折' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_049',
    platform: 'dianping',
    openHours: { weekday: '10:00-20:00', weekend: '09:30-21:00' },
    externalId: 'sh_lh_049',
  },
  {
    name: '星巴克甄选店(龙华)',
    city: '上海',
    district: '徐汇区',
    neighborhood: '滨江步道',
    address: '徐汇滨江龙华段',
    lat: 31.1647,
    lng: 121.4677,
    category: '咖啡奶茶',
    avgPrice: 55,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/starbucks.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '下午3-5点第2杯半价' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_050',
    platform: 'dianping',
    openHours: { weekday: '07:00-21:00', weekend: '07:30-21:30' },
    externalId: 'sh_lh_050',
  },
  {
    name: '西岸风之谷体育公园',
    city: '上海',
    district: '徐汇区',
    neighborhood: '滨江步道',
    address: '徐汇区徐汇滨江',
    lat: 31.1641,
    lng: 121.4671,
    category: '户外公园',
    avgPrice: 20,
    rating: 4.5,
    imageUrl: 'https://p0.meituan.net/brandlogons/fenzhigu.jpg',
    discountTypes: ['促销'],
    discounts: { 促销: '工作日早场免费' },
    externalUrl: 'https://www.dianping.com/shop/sh_lh_051',
    platform: 'dianping',
    openHours: { weekday: '06:00-22:00', weekend: '06:00-22:00' },
    externalId: 'sh_lh_051',
  },
  {
    name: '龙华广场（青铜花苞）',
    city: '上海',
    district: '徐汇区',
    neighborhood: '滨江步道',
    address: '徐汇区龙华路2778号龙华广场',
    lat: 31.19,
    lng: 121.4545,
    category: '户外公园',
    avgPrice: 0,
    rating: 4.4,
    imageUrl: 'https://p0.meituan.net/brandlogons/longhuaguangchang.jpg',
    discountTypes: [],
    discounts: { 特色: '免费·散步打卡' },
    externalUrl: '',
    platform: 'dianping',
    openHours: { weekday: '00:00-24:00', weekend: '00:00-24:00' },
    externalId: 'sh_lh_052',
  },
];

@Injectable()
export class ShopSeedService implements OnApplicationBootstrap {
  private readonly logger = new Logger(ShopSeedService.name);

  constructor(
    @InjectRepository(Shop) private readonly shopRepo: Repository<Shop>,
  ) {}

  async onApplicationBootstrap(): Promise<void> {
    const count = await this.shopRepo.count();
    const hasShanghai =
      count > 0
        ? (await this.shopRepo.findOne({ where: { city: '上海' } })) !== null
        : false;
    if (count > 0 && hasShanghai) {
      this.logger.log(
        `Shop table already has Shanghai data (${count} rows), skipping seed`,
      );
      return;
    }
    if (count > 0) {
      this.logger.log(
        'Replacing old city data with Shanghai Longhua Street shops...',
      );
    } else {
      this.logger.log('Seeding Shanghai Longhua Street shop data...');
    }
    await this.reseed();
    this.logger.log(`Seeded ${SEED_SHOPS.length} shops`);
  }

  async seedShops(): Promise<void> {
    for (const s of SEED_SHOPS) {
      const existing = await this.shopRepo.findOneBy({
        externalId: s.externalId,
      });
      if (existing) continue;
      await this.shopRepo.save(
        this.shopRepo.create({
          name: s.name,
          city: s.city,
          district: s.district,
          neighborhood: s.neighborhood,
          address: s.address,
          lat: s.lat,
          lng: s.lng,
          category: s.category,
          avgPrice: s.avgPrice,
          rating: s.rating,
          imageUrl: s.imageUrl,
          discountTypes: s.discountTypes,
          discounts: s.discounts,
          externalUrl: s.externalUrl,
          openHours: s.openHours,
          externalId: s.externalId,
        }),
      );
    }
  }

  async reseed(): Promise<void> {
    await this.shopRepo.clear();
    await this.seedShops();
  }
}
